# permissions for end users to view redissentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redissentinel-viewer-role
rules:
- apiGroups:
  - redis.redis.operator
  resources:
  - redissentinels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.redis.operator
  resources:
  - redissentinels/status
  verbs:
  - get
