---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - configmaps
  - endpoints
  - events
  - pods
  - secrets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - redis.redis.operator
  resources:
  - redisreplications
  - redissentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis.operator
  resources:
  - redisreplications/finalizers
  - redissentinels/finalizers
  verbs:
  - update
- apiGroups:
  - redis.redis.operator
  resources:
  - redisreplications/status
  - redissentinels/status
  verbs:
  - get
  - patch
  - update
