---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redis-redis-operator-v1-redisreplication
  failurePolicy: Fail
  name: mredisreplication.kb.io
  rules:
  - apiGroups:
    - redis.redis.operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redisreplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redis-redis-operator-v1-redissentinel
  failurePolicy: Fail
  name: mredissentinel.kb.io
  rules:
  - apiGroups:
    - redis.redis.operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redissentinels
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redis-redis-operator-v1-redisreplication
  failurePolicy: Fail
  name: vredisreplication.kb.io
  rules:
  - apiGroups:
    - redis.redis.operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redisreplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redis-redis-operator-v1-redissentinel
  failurePolicy: Fail
  name: vredissentinel.kb.io
  rules:
  - apiGroups:
    - redis.redis.operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redissentinels
  sideEffects: None
