apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-monitor
  namespace: redis-database
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redisreplication-service
  endpoints:
  - port: redis-exporter
    interval: 30s
    path: /metrics
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - redis-database
